### Analisis de rendimiento - Fútbol Femenino

El equipo de fútbol femenino "Estrellas FC" quiere evaluar el rendimiento de sus jugadoras a lo largo de la última temporada para planificar entrenamientos, formaciones y estrategias para los próximos partidos. Como parte del equipo de análisis de datos del club, tu tarea es analizar el conjunto de datos de las asistencias utilizando Python y Numpy.

Objetivos:

- Analizar la contribución de cada jugadora al equipo.
- Identificar las jugadoras con mejor y peor rendimiento.
- Evaluar la consistencia del rendimiento de las jugadoras a lo largo de la temporada.
- Desarrollar recomendaciones para el entrenamiento y la formación basadas en los resultados.

In [3]:
# Importa las librerías necesaria para el desarrollo de nuestro ejercicio.

import numpy as np

In [4]:
# Crea un array bidimensional 'asistencias' para las 11 jugadoras titulares a lo largo de 30 partidos.

asistencias_ceros=np.zeros((30,11))
print(asistencias_ceros)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.

In [5]:
asistencias=np.random.randint(1,11, size=(30,11))
print(asistencias)

[[ 4  4  1  8  6  3  6  5  5  6  7]
 [10  2  3  7  2  7  5  2  3  2  2]
 [ 6  3  4  2  7  2  7  7 10 10  2]
 [ 4  1  1 10  7  6  2  9  6  6 10]
 [ 5  6 10  7  2  7  2  8  7  7  7]
 [ 4  1  9  8  4  6  2  4  7  8  1]
 [ 7  5  8  3  4  6  9  9  5  2  9]
 [ 8  2  9  4  5  9  8 10  2  1  9]
 [10  7  8  9  5  9  3  7  7  2  7]
 [ 9  5  6  5  1  6 10  4  4  3 10]
 [ 7  2  9 10  5  6  6  3  9  7  5]
 [10  7  1  6 10  5 10  7 10  6  5]
 [ 5  2  3  7  5  8  7  2 10  3  6]
 [ 1  2  8 10  1 10  2  8  1  6  3]
 [ 8  6  3  7  9  5  4  7  3  1 10]
 [ 1  5  6  3  2  9  7  5  5  6  3]
 [ 7  4  1  7  2  6  2  1 10 10  3]
 [10  2  3  2 10  1 10 10  4  6  2]
 [ 2  1  1  2  7  6  3  7  6  1  4]
 [ 9  4  1  7  5  4  5  9  2  4  8]
 [ 2  9  8  2  2  2  1  4  7  6  1]
 [ 3  8  3  1  5  1  6  6  3 10  5]
 [10  9 10  8  6  2  3  6  5  4  5]
 [ 2  4  1  3  4  4  8  7  7  8  3]
 [ 1  7 10 10  7  3  9  8 10  4  4]
 [ 1  8 10  9  4  7  1  9  1  2  9]
 [ 1  3  1  3  1  7  7  5  9  6  4]
 [ 5  2  5  8  4  6  9  5  5

In [6]:
# Calcula el total de asistencias por jugadora a lo largo de la temporada.
total_asistencias_por_jugadora = np.sum(asistencias, axis=0) #Axis nos tenermina si por la columna (0) o por fila (1)
print(total_asistencias_por_jugadora)

[166 138 158 180 143 170 170 179 177 156 154]


In [7]:
for i, total in enumerate(total_asistencias_por_jugadora):
    print(f"Jugadora {i+1}: {total} asistencias en total")

Jugadora 1: 166 asistencias en total
Jugadora 2: 138 asistencias en total
Jugadora 3: 158 asistencias en total
Jugadora 4: 180 asistencias en total
Jugadora 5: 143 asistencias en total
Jugadora 6: 170 asistencias en total
Jugadora 7: 170 asistencias en total
Jugadora 8: 179 asistencias en total
Jugadora 9: 177 asistencias en total
Jugadora 10: 156 asistencias en total
Jugadora 11: 154 asistencias en total


In [8]:
# Corrige los datos en el partido número 20, aumenta la cantidad de asistencias de la jugadora 5 en 2.
print(asistencias[19,4])
asistencias[20-1,5-1]+=2
print(asistencias[19,4])

5
7


In [9]:
# Calcula el promedio de asistencia por jugadora a lo largo de la temporada.

promedio_asistencia_por_jugadora=np.mean(asistencias,axis=0)
print(np.around(promedio_asistencia_por_jugadora,decimals=2)) #Otra manera de castear

[5.53 4.6  5.27 6.   4.83 5.67 5.67 5.97 5.9  5.2  5.13]


In [10]:
for i, promedio in enumerate(promedio_asistencia_por_jugadora):
    print(f"Jugadora {i+1}: promedio de asistencias {promedio:.2f}") #Lo casteo para tener 2 decimales

Jugadora 1: promedio de asistencias 5.53
Jugadora 2: promedio de asistencias 4.60
Jugadora 3: promedio de asistencias 5.27
Jugadora 4: promedio de asistencias 6.00
Jugadora 5: promedio de asistencias 4.83
Jugadora 6: promedio de asistencias 5.67
Jugadora 7: promedio de asistencias 5.67
Jugadora 8: promedio de asistencias 5.97
Jugadora 9: promedio de asistencias 5.90
Jugadora 10: promedio de asistencias 5.20
Jugadora 11: promedio de asistencias 5.13


In [11]:
# Selecciona y muestra las asistencias de las jugadoras en el final de la temporada (los últimos 10 partidos).

print(asistencias[20:30,])

[[ 2  9  8  2  2  2  1  4  7  6  1]
 [ 3  8  3  1  5  1  6  6  3 10  5]
 [10  9 10  8  6  2  3  6  5  4  5]
 [ 2  4  1  3  4  4  8  7  7  8  3]
 [ 1  7 10 10  7  3  9  8 10  4  4]
 [ 1  8 10  9  4  7  1  9  1  2  9]
 [ 1  3  1  3  1  7  7  5  9  6  4]
 [ 5  2  5  8  4  6  9  5  5  7  1]
 [ 9  8  5  9 10  9  6  3  7  5  8]
 [ 5  9 10  3  1  8 10  2  7  7  1]]


In [12]:
final_de_temporada=asistencias[-10:,]
print(final_de_temporada)

[[ 2  9  8  2  2  2  1  4  7  6  1]
 [ 3  8  3  1  5  1  6  6  3 10  5]
 [10  9 10  8  6  2  3  6  5  4  5]
 [ 2  4  1  3  4  4  8  7  7  8  3]
 [ 1  7 10 10  7  3  9  8 10  4  4]
 [ 1  8 10  9  4  7  1  9  1  2  9]
 [ 1  3  1  3  1  7  7  5  9  6  4]
 [ 5  2  5  8  4  6  9  5  5  7  1]
 [ 9  8  5  9 10  9  6  3  7  5  8]
 [ 5  9 10  3  1  8 10  2  7  7  1]]


In [13]:
# Calcula las asistencias del final de la temporada y comparalo vs las asistencias del inicio. ¿Fue mejor?
principio_de_temporada=asistencias[0:10,]
if np.sum(principio_de_temporada) > np.sum(final_de_temporada):
        print('El inicio de la temporada fue mejor')
elif np.sum(asistencias[0:10]) < np.sum(asistencias[-10:,]):
    print('El final de la temporada fue mejor')
else:
    print('El principio y final de la temporada muestran el mismo resultado')
    

El inicio de la temporada fue mejor


In [19]:
print(sum(principio_de_temporada))
print(sum(final_de_temporada))

[67 36 59 63 43 61 54 65 56 47 64]
[39 67 63 56 44 49 60 55 61 59 41]


In [20]:
print(np.sum(principio_de_temporada))
print(np.sum(final_de_temporada))

615
594


In [15]:
# Crea una máscara que identificar partidos en los que cualquier jugadora superó las 5 asistencias.

mascara_jugadores_rendimiento_superior= asistencias >5
print(mascara_jugadores_rendimiento_superior)

[[False False False  True  True False  True False False  True  True]
 [ True False False  True False  True False False False False False]
 [ True False False False  True False  True  True  True  True False]
 [False False False  True  True  True False  True  True  True  True]
 [False  True  True  True False  True False  True  True  True  True]
 [False False  True  True False  True False False  True  True False]
 [ True False  True False False  True  True  True False False  True]
 [ True False  True False False  True  True  True False False  True]
 [ True  True  True  True False  True False  True  True False  True]
 [ True False  True False False  True  True False False False  True]
 [ True False  True  True False  True  True False  True  True False]
 [ True  True False  True  True False  True  True  True  True False]
 [False False False  True False  True  True False  True False  True]
 [False False  True  True False  True False  True False  True False]
 [ True  True False  True  True Fa

In [16]:
# Filtra  el valor de esas asistencias en cada partido.

valors_superiores=asistencias[mascara_jugadores_rendimiento_superior]
print(valors_superiores)

[ 8  6  6  6  7 10  7  7  6  7  7  7 10 10 10  7  6  9  6  6 10  6 10  7
  7  8  7  7  7  9  8  6  7  8  7  8  6  9  9  9  8  9  9  8 10  9 10  7
  8  9  9  7  7  7  9  6  6 10 10  7  9 10  6  6  9  7 10  7  6 10 10  7
 10  6  7  8  7 10  6  8 10 10  8  6  8  6  7  9  7 10  6  9  7  6  7  7
  6 10 10 10 10 10 10  6  7  6  7  6  9  7  7  9  8  9  8  7  6  8  6  6
 10 10  9 10  8  6  6  8  7  7  8  7 10 10  7  9  8 10  8 10  9  7  9  9
  7  7  9  6  8  6  9  7  9  8  9 10  9  6  7  8  9 10  8 10  7  7]


In [17]:
# Calcula la varianza y la desviación estándar de las asistencias por jugadora

varianza_jugadores=np.var(asistencias, axis=0)
desviacion_estandar_jugadores=np.std(asistencias, axis=0)
print(varianza_jugadores)
print(desviacion_estandar_jugadores)



[10.31555556  6.90666667 11.92888889  8.4         7.53888889  6.22222222
  8.75555556  6.43222222  7.55666667  7.02666667  8.78222222]
[3.21178386 2.62805378 3.45382236 2.89827535 2.74570371 2.49443826
 2.9589788  2.53618261 2.74893919 2.65078605 2.96348144]


In [18]:
for i, (varianza, desviacion) in enumerate(zip(varianza_jugadores,desviacion_estandar_jugadores)):
    print(f"Para la jugadora {i+1} la varianza es de {varianza:.2f} y la desviacion estandar de {desviacion:.2f}")

Para la jugadora 1 la varianza es de 10.32 y la desviacion estandar de 3.21
Para la jugadora 2 la varianza es de 6.91 y la desviacion estandar de 2.63
Para la jugadora 3 la varianza es de 11.93 y la desviacion estandar de 3.45
Para la jugadora 4 la varianza es de 8.40 y la desviacion estandar de 2.90
Para la jugadora 5 la varianza es de 7.54 y la desviacion estandar de 2.75
Para la jugadora 6 la varianza es de 6.22 y la desviacion estandar de 2.49
Para la jugadora 7 la varianza es de 8.76 y la desviacion estandar de 2.96
Para la jugadora 8 la varianza es de 6.43 y la desviacion estandar de 2.54
Para la jugadora 9 la varianza es de 7.56 y la desviacion estandar de 2.75
Para la jugadora 10 la varianza es de 7.03 y la desviacion estandar de 2.65
Para la jugadora 11 la varianza es de 8.78 y la desviacion estandar de 2.96
