In [1]:
import numpy as np

# Número de participantes en cinco clases deportivas durante una semana
participantes = np.array([12, 7, 25, 19, 9])

# Creación de una máscara para identificar clases con alta demanda
alta_demanda = participantes > 15

print("Clases con alta demanda:", alta_demanda)


Clases con alta demanda: [False False  True  True False]


In [2]:
# Usando la máscara para seleccionar el número de participantes en clases de alta demanda
participantes_alta_demanda = participantes[alta_demanda]

print("Número de participantes en clases de alta demanda:", participantes_alta_demanda)


Número de participantes en clases de alta demanda: [25 19]


In [3]:
#Tambien pordemos escribir el codigo dentro del corchete (aprendido video Bryan)
print(participantes[participantes >15])
alta_demanda2= participantes[participantes >15]
print(alta_demanda2)

[25 19]
[25 19]


In [4]:
type(participantes)   #Comprobando informacion por mi cuenta
type(alta_demanda)
type(participantes_alta_demanda)

numpy.ndarray

np.triu
La función np.triu devuelve la parte triangular superior de un array, es decir, toma un array y devuelve un nuevo array con los elementos por debajo de la diagonal k-ésima igualados a cero, esencialmente manteniendo la parte triangular superior de la matriz. 

In [5]:
# Matriz de resultados de partidos entre 4 equipos
resultados = np.array([[0, 2, 1, 3],
                       [2, 0, 4, 1],
                       [1, 4, 0, 5],
                       [3, 1, 5, 0]])

# Mantenemos solo la parte superior para simplificar el análisis
resultados_triangular = np.triu(resultados)

print("Resultados en formato triangular superior:\n", resultados_triangular)


Resultados en formato triangular superior:
 [[0 2 1 3]
 [0 0 4 1]
 [0 0 0 5]
 [0 0 0 0]]


np.ones_like
La función np.ones_like crea un nuevo array con la misma forma y tipo que un array dado, llenándolo todo con unos. Es útil para crear máscaras iniciales o arrays de pesos cuando trabajamos con operaciones que involucran matrices o arrays de dimensiones específicas.

In [6]:
# Ejemplo de un plan de entrenamiento para una semana (7 días)
plan_entrenamiento = np.array([3, 3, 3, 3, 3, 3, 3])  # 3 horas por día

# Usando np.ones_like para crear una nueva agenda con el mismo formato
nueva_agenda = np.ones_like(plan_entrenamiento) * 2  # Ahora con 2 horas por día

print("Nueva agenda de entrenamientos:\n", nueva_agenda)


Nueva agenda de entrenamientos:
 [2 2 2 2 2 2 2]


Otros usos avanzados de máscaras
Las máscaras no se limitan a condiciones simples; pueden combinarse usando operadores lógicos como & (y), | (o), ~ (no), para construir condiciones más complejas.

Combinación de máscaras

Selección de atletas para un programa de entrenamiento especial
Supongamos que el Club Deportivo Deporte y Vida quiere seleccionar atletas para un programa de entrenamiento especial basado en dos criterios: la asistencia regular a las sesiones de entrenamiento y un nivel mínimo de rendimiento.

Consideraremos una asistencia superior al 80% como regular.

Un nivel de rendimiento se mide en puntos, donde 50 puntos es el mínimo requerido.

In [7]:
# Datos ficticios de asistencia (en porcentaje) y rendimiento (en puntos) de atletas
asistencia = np.array([85, 90, 75, 60, 95, 80])
rendimiento = np.array([55, 60, 45, 50, 65, 48])

# Máscaras para cada condición
mascara_asistencia = asistencia > 80
mascara_rendimiento = rendimiento >= 50

# Combinación de máscaras para identificar atletas que cumplen ambos criterios
mascara_combinada = mascara_asistencia & mascara_rendimiento

print("Atletas seleccionados para el programa especial:", mascara_combinada)
# En este ejemplo, la combinación de máscaras permite identificar atletas que cumplen con ambos 
# criterios establecidos para la selección en el programa de entrenamiento.


Atletas seleccionados para el programa especial: [ True  True False False  True False]


In [8]:
print(mascara_asistencia)
print(mascara_rendimiento)
print(mascara_combinada)
probando_combinacion=(asistencia>80) & (rendimiento>=50) #Podemos utilizarlo de manera directa
print(probando_combinacion)

[ True  True False False  True False]
[ True  True False  True  True False]
[ True  True False False  True False]
[ True  True False False  True False]


In [9]:
#Ejemplo. Invento datos para ver si entendi
deportistas_miejemplo=np.array(['Diego','Carlos','Armando','Fernando','Andres','Miguel'])

In [10]:
deportista_invitados = deportistas_miejemplo[mascara_combinada] #Sigo con mi ejemplo de aprendizaje.
print(deportista_invitados)
print(deportistas_miejemplo[(asistencia>80) & (rendimiento>=50)]) #Mas directo aun

['Diego' 'Carlos' 'Andres']
['Diego' 'Carlos' 'Andres']


Asignar un valor usando una máscara
Las máscaras también se pueden utilizar para asignar valores a elementos específicos de un array, lo que las hace útiles para la limpieza y preparación de datos.

Ajuste del plan de entrenamiento basado en rendimiento
Imaginemos que el Club Deportivo Deporte y Vida decide aumentar las horas de entrenamiento para aquellos atletas cuyo rendimiento está por debajo del umbral deseado, como medida para mejorar su desempeño.

In [11]:
# Horas actuales de entrenamiento por atleta
horas_entrenamiento = np.array([5, 5, 5, 5, 5, 5])

# Aumentamos las horas de entrenamiento para atletas con rendimiento bajo
# Usando la máscara de rendimiento negada (~), para seleccionar rendimientos bajos
horas_entrenamiento[~mascara_rendimiento] += 2
#Al utilizar el (~) se cambian los valores boleanos, aplicando la adicion (suma) a los que ahora son True pero
# originalmente eran False
print("Horas de entrenamiento ajustadas:", horas_entrenamiento)
#En este ejemplo, utilizamos la máscara para asignar un valor específico (en este caso, aumentar las horas 
# de entrenamiento) solo a aquellos atletas que no cumplen con el criterio de rendimiento establecido.


Horas de entrenamiento ajustadas: [5 5 7 5 5 7]
