Crear una matriz de manera directa

Crear una matriz que representa los puntos anotados por tres equipos en cinco partidos

In [2]:
import numpy as np
puntos_por_partido = np.array([
    [10, 12, 15, 14, 13],  # Equipo 1
    [9, 11, 8, 16, 14],    # Equipo 2
    [12, 15, 10, 15, 14]   # Equipo 3
])

print("Puntos por partido:\n", puntos_por_partido)


Puntos por partido:
 [[10 12 15 14 13]
 [ 9 11  8 16 14]
 [12 15 10 15 14]]


Usar np.zeros()

Crea una matriz de ceros. Esto es útil cuando necesitas una matriz de un tamaño específico para inicializar tus cálculos.
Crear una matriz de 3x5 llena de ceros

In [3]:
matriz_ceros = np.zeros((3, 5))

print("Matriz de ceros:\n", matriz_ceros)


Matriz de ceros:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


Usar np.ones()
Similar a np.zeros(), pero llena la matriz con unos.
Crear una matriz de 3x5 llena de unos


In [16]:
matriz_ceros[0,0]=np.sum(puntos_por_partido) #Sumamos los puntos y los guardamos en la cordenada (0,0)
print(matriz_ceros)

[[188.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.]]


In [4]:
matriz_unos = np.ones((3, 5))

print("Matriz de unos:\n", matriz_unos)


Matriz de unos:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


Usar np.eye()

Crea una matriz identidad de tamaño n x n. La matriz identidad es una matriz cuadrada llena de ceros excepto por unos en la diagonal principal. Es muy útil en operaciones de álgebra lineal.
Crear una matriz identidad de 4x4

In [5]:
matriz_identidad = np.eye(4)

print("Matriz identidad:\n", matriz_identidad)


Matriz identidad:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Usar np.full()

Crea una matriz llenada con un valor específico.
Crear una matriz de 3x5 llena con el número 7

In [6]:
# Crear una matriz de 3x5 llena con el número 7
matriz_llena = np.full((3, 5), 7)

print("Matriz llena con sietes:\n", matriz_llena)


Matriz llena con sietes:
 [[7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]]


np.matrix

La función np.matrix crea un objeto de matriz a partir de una cadena de texto o una secuencia de Python como listas. Las matrices creadas con np.matrix son estrictamente bidimensionales, y las operaciones matriciales como la multiplicación se realizan utilizando el operador *, que es diferente del comportamiento de los arrays ndarray, donde * realiza una multiplicación elemento a elemento.

np.mat

np.mat es un alias para np.matrix, y su función es la misma: facilitar la creación de objetos de matriz. Puede ser más conveniente para convertir arrays existentes en objetos de matriz.

Creación de una matriz usando np.matrix

In [8]:
# Creación de una matriz a partir de una lista
matriz_a = np.matrix([[1, 2], [3, 4]])
print("Matriz A:\n", matriz_a)

# Creación de una matriz a partir de una cadena de texto
matriz_b = np.matrix('5 6; 7 8')
print("Matriz B:\n", matriz_b)


Matriz A:
 [[1 2]
 [3 4]]
Matriz B:
 [[5 6]
 [7 8]]


Multiplicación de matrices
Una de las ventajas de usar np.matrix sobre ndarray es la simplicidad para realizar la multiplicación de matrices usando el operador *.

In [9]:
# Multiplicación de matrices
resultado = matriz_a * matriz_b
print("Resultado de la multiplicación de A y B:\n", resultado)


Resultado de la multiplicación de A y B:
 [[19 22]
 [43 50]]


Conversión de ndarray a np.matrix Usando np.mat
Si ya tienes un array ndarray y deseas aprovechar las operaciones específicas de matrices, puedes convertirlo usando np.mat.

In [12]:
# Creando un ndarray
array_c = np.array([[9, 8], [7, 6]])

# Convirtiendo ndarray a np.matrix
matriz_c = np.asmatrix(array_c)      #`np.mat` was removed in the NumPy 2.0 release. Use `np.asmatrix` instead.
print("Matriz C (convertida de ndarray):\n", matriz_c)


Matriz C (convertida de ndarray):
 [[9 8]
 [7 6]]


Recomendaciones

Aunque np.matrix y np.mat pueden ser útiles para ciertas aplicaciones, la comunidad de Numpy recomienda utilizar arrays bidimensionales ndarray para una mayor flexibilidad y consistencia, especialmente para nuevos desarrollos. Esto se debe a que ndarray es la estructura de datos central de Numpy y soporta una gama más amplia de operaciones. Para operaciones matriciales como la multiplicación de matrices, puedes usar np.dot, np.matmul o el operador @ con ndarray, lo cual es preferible en la práctica moderna de programación con Numpy.

Operaciones con matrices

Transposición
transpuesta = matriz1.T

In [17]:
import numpy as np

# Creación de una matriz
matriz1 = np.array([[1, 2], [3, 4], [5, 6]])
print("Matriz Original:\n", matriz1)

# Transposición de la matriz
transpuesta = matriz1.T
print("Matriz Transpuesta:\n", transpuesta)


Matriz Original:
 [[1 2]
 [3 4]
 [5 6]]
Matriz Transpuesta:
 [[1 3 5]
 [2 4 6]]


Inversa
inversa = matriz1.I

In [18]:
# Creación de una matriz cuadrada
matriz_cuadrada = np.array([[4, 7], [2, 6]])

# Cálculo de la inversa
inversa = np.linalg.inv(matriz_cuadrada)
print("Inversa de la Matriz:\n", inversa)

# Verificación A * A^-1 = I
producto = np.dot(matriz_cuadrada, inversa)
print("Producto de Matriz por su Inversa:\n", producto)


Inversa de la Matriz:
 [[ 0.6 -0.7]
 [-0.2  0.4]]
Producto de Matriz por su Inversa:
 [[ 1.00000000e+00 -1.11022302e-16]
 [ 1.11022302e-16  1.00000000e+00]]


Determinante
determinante = np.linalg.det(matriz1)

In [19]:
# Creación de una matriz cuadrada
matriz_cuadrada = np.array([[4, 7], [2, 6]])

# Cálculo del determinante
determinante = np.linalg.det(matriz_cuadrada)
print("Determinante de la Matriz:", determinante)


Determinante de la Matriz: 10.000000000000002
